= Doing a Blue-Green Demo

This application leverages the colors blue and green to demonstrate the dynamic routing and load balancing capabilities of Cloud Foundry in a Blue-Green Deployment Scenario.

Demonstrate https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/blue-green.html/[Blue-Green Deployments] on Cloud Foundry with this simple (one Groovy file) Spring Boot CLI application!

== Running Locally

* Install the http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-installing-the-cli[latest Spring Boot CLI].
* Run:

----
$ spring run web/app.groovy
----

== Step 1: Push an App

Use the cf CLI to push the application. Name the application "Blue" with the subdomain "demo."

----
$ cf push Blue -n demo
----

Blue is now running on Cloud Foundry.
The CF Router sends all traffic for demo.local.pcfdev.io traffic to Blue.

== Step 2: Update App and Push

Now make a change to the application, Modify +app.groovy+ to use the color green, replace the color "blue" on the web page with "green".  (line 3):

----
String color = "green"
----

Run cf push again, but use the name "Green" for the application and provide a different subdomain to create a temporary route:

----
$ cf push Green -n demo-temp
----

After this push:

Two instances of our application are now running on Cloud Foundry: the original Blue and the updated Green.
The CF Router still sends all traffic for demo.local.pcfdev.io traffic to Blue. The router now also sends any traffic for demo-temp.local.pcfdev.io to Green.


== Step 3: Map Original Route to Green

Now that both apps are up and running, switch the router so all incoming requests go to the Green app and the Blue app. Do this by mapping the original URL route (demo.local.pcfdev.io) to the Green application.

----
$ cf map-route Green local.pcfdev.io -n demo
----

Binding demo.local.pcfdev.io to Green...
OK

After the cf map-route command :

The CF Router continues to send traffic for demo-temp.local.pcfdev.io to Green.
The CF Router immediately begins to load balance traffic for demo.local.pcfdev.io between Blue and Green.

== Step 4: Unmap Route to Blue

Once you verify Green is running as expected, stop routing requests to Blue using the cf unmap-route command:

----
$ cf unmap-route Blue local.pcfdev.io -n demo
----

Unbinding demo.local.pcfdev.io from blue... OK
After cf unmap-route command:

The CF Router stops sending traffic to Blue. Instead, it routes all traffic to demo.local.pcfdev.io to Green:

== Step 5: Remove Temporary Route to Green

You can now use cf unmap-route to remove the route to demo-temp.local.pcfdev.io. You can also decommission Blue, or keep it in case you need to roll back your changes.
